modLoader="javafml"
loaderVersion="[31,)"

[[mods]]
modId="random"
version="1.0.0"
displayName="Random"
credits="Created using mod maker MCreator - https://mcreator.net/about"
displayURL="https://mcreator.net"
authors="wiene, MCreator"

[[dependencies.random]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.15.2]"
    ordering="NONE"
    side="BOTH"




